//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
  using Newtonsoft.Json;
  using System;
  using System.Collections.Generic;

  public partial class Article
  {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Article()
    {
      Id = Guid.NewGuid();
      this.Images = new List<Image>();
    }

    public System.Guid Id { get; set; }
    public string Title { get; set; }
    [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "datetime2")]
    public Nullable<System.DateTime> Date { get; set; }
    public string Summary { get; set; }
    public string Content { get; set; }
    public bool IsLead { get; set; }
    public System.Guid UserId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    public virtual IList<Image> Images { get; set; }
    [JsonIgnore]
    public virtual Account Accounts { get; set; }
  }
}
